//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBaseContact.h"


@interface CContact : CBaseContact <NSCoding>
{
    unsigned int m_uiChatRoomStatus;
    NSString *m_nsChatRoomMemList;
    unsigned int m_uiChatRoomMaxCount;
    unsigned int m_uiChatRoomVersion;
    NSString *m_nsChatRoomData;
    NSString *m_nsCountry;
    NSString *m_nsProvince;
    NSString *m_nsCity;
    NSString *m_nsSignature;
    unsigned int m_uiCertificationFlag;
    NSString *m_nsCertificationInfo;
    NSString *m_nsOwner;
    NSString *m_nsWeiboAddress;
    NSString *m_nsWeiboNickName;
    unsigned int m_uiWeiboFlag;
    NSString *m_nsFBNickName;
    NSString *m_nsFBID;
    unsigned int m_uiNeedUpdate;
    NSString *m_nsWCBGImgObjectID;
    int m_iWCFlag;
    NSString *m_pcWCBGImgID;
    NSString *m_nsExternalInfo;
    NSString *m_nsBrandSubscriptConfigUrl;
    unsigned int m_uiBrandSubscriptionSettings;
    NSString *m_nsBrandIconUrl;
    _Bool m_isExtInfoValid;
    NSDictionary *externalInfoJSONCache;
    _Bool m_isShowRedDot;
    NSString *m_nsMobileHash;
    NSString *m_nsMobileFullHash;
    NSString *m_nsLinkedInID;
    NSString *m_nsLinkedInName;
    NSString *m_nsLinkedInPublicUrl;
    unsigned int m_uiDeleteFlag;
    NSString *m_nsDescription;
    NSString *m_nsCardUrl;
    NSString *m_nsWorkID;
    NSString *m_nsLabelIDList;
    NSArray *m_arrPhoneItem;
    NSString *m_nsWeiDianInfo;
    NSDictionary *_m_dicWeiDianInfo;
}

+ (void)HandleUsrImgPB:(id)arg1 Contatct:(id)arg2 DocPath:(id)arg3;
+ (id)SubscriptedBrandsFromString:(id)arg1;
+ (id)genChatRoomName:(id)arg1;
+ (id)getChatRoomMember:(id)arg1;
+ (unsigned long long)getChatRoomMemberCount:(id)arg1;
+ (id)getChatRoomMemberWithoutMyself:(id)arg1;
+ (id)getContactTypeImage:(unsigned int)arg1 isFrontPage:(_Bool)arg2;
+ (id)getMicroBlogUsrDisplayName:(id)arg1;
+ (void)initialize;
+ (_Bool)isHeadImgUpdated:(id)arg1 Local:(id)arg2;
+ (id)parseContactKey:(id)arg1;
- (_Bool)IsAddFromLbs;
- (_Bool)IsAddFromShake;
- (_Bool)IsUserInChatRoom:(id)arg1;
- (long long)compareForFavourGroup:(id)arg1;
- (_Bool)copyFieldFromContact:(id)arg1;
- (_Bool)copyPatialFieldFromContact:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (id)externalInfoJSONCache;
- (_Bool)genContactFromShareCardMsgWrap:(id)arg1;
- (void)genContactFromShareCardMsgWrapContent:(id)arg1;
- (id)getChatRoomMemberDisplayName:(id)arg1;
- (id)getChatRoomMemberNickName:(id)arg1;
- (id)getChatRoomMembrGroupNickName:(id)arg1;
- (id)getLabelIDList;
- (id)getMobileDisplayName;
- (id)getMobileList;
- (id)getMobileNumString;
- (id)getNewChatroomData;
- (id)getNormalContactDisplayDesc;
- (id)getValueTypeTable;
- (_Bool)hasMatchHashPhone;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithModContact:(id)arg1;
- (id)initWithShareCardMsgWrap:(id)arg1;
- (id)initWithShareCardMsgWrapContent:(id)arg1;
- (_Bool)isAccountDeleted;
- (_Bool)isAdmin;
- (_Bool)isBrandContact;
- (_Bool)isChatStatusNotifyOpen;
- (_Bool)isContactFrozen;
- (_Bool)isContactSessionTop;
- (_Bool)isContactTypeShouldDelete;
- (_Bool)isHasMobile;
- (_Bool)isHasWeiDian;
- (_Bool)isHolderContact;
- (_Bool)isIgnoreBrandContat;
- (_Bool)isLocalizedContact;
- (_Bool)isMyContact;
- (_Bool)isShowChatRoomDisplayName;
- (_Bool)isShowLinkedIn;
- (_Bool)isVerified;
- (_Bool)isVerifiedBrandContact;
@property(retain, nonatomic) NSArray *m_arrPhoneItem; // @synthesize m_arrPhoneItem;
@property(readonly, nonatomic) NSDictionary *m_dicWeiDianInfo; // @synthesize m_dicWeiDianInfo=_m_dicWeiDianInfo;
@property(nonatomic) int m_iWCFlag; // @synthesize m_iWCFlag;
@property(nonatomic) _Bool m_isExtInfoValid; // @synthesize m_isExtInfoValid;
@property(nonatomic) _Bool m_isShowRedDot; // @synthesize m_isShowRedDot;
@property(retain, nonatomic) NSString *m_nsBrandIconUrl; // @synthesize m_nsBrandIconUrl;
@property(retain, nonatomic) NSString *m_nsBrandSubscriptConfigUrl; // @synthesize m_nsBrandSubscriptConfigUrl;
@property(retain, nonatomic) NSString *m_nsCardUrl; // @synthesize m_nsCardUrl;
@property(retain, nonatomic) NSString *m_nsCertificationInfo; // @synthesize m_nsCertificationInfo;
@property(retain, nonatomic) NSString *m_nsChatRoomData; // @synthesize m_nsChatRoomData;
@property(retain, nonatomic) NSString *m_nsChatRoomMemList; // @synthesize m_nsChatRoomMemList;
@property(retain, nonatomic) NSString *m_nsCity; // @synthesize m_nsCity;
@property(retain, nonatomic) NSString *m_nsCountry; // @synthesize m_nsCountry;
@property(retain, nonatomic) NSString *m_nsDescription; // @synthesize m_nsDescription;
@property(retain, nonatomic) NSString *m_nsExternalInfo; // @synthesize m_nsExternalInfo;
@property(retain, nonatomic) NSString *m_nsFBID; // @synthesize m_nsFBID;
@property(retain, nonatomic) NSString *m_nsFBNickName; // @synthesize m_nsFBNickName;
@property(retain, nonatomic) NSString *m_nsLabelIDList; // @synthesize m_nsLabelIDList;
@property(retain, nonatomic) NSString *m_nsLinkedInID; // @synthesize m_nsLinkedInID;
@property(retain, nonatomic) NSString *m_nsLinkedInName; // @synthesize m_nsLinkedInName;
@property(retain, nonatomic) NSString *m_nsLinkedInPublicUrl; // @synthesize m_nsLinkedInPublicUrl;
@property(retain, nonatomic) NSString *m_nsMobileFullHash; // @synthesize m_nsMobileFullHash;
@property(retain, nonatomic) NSString *m_nsMobileHash; // @synthesize m_nsMobileHash;
@property(retain, nonatomic) NSString *m_nsOwner; // @synthesize m_nsOwner;
@property(retain, nonatomic) NSString *m_nsProvince; // @synthesize m_nsProvince;
@property(retain, nonatomic) NSString *m_nsSignature; // @synthesize m_nsSignature;
@property(retain, nonatomic) NSString *m_nsWCBGImgObjectID; // @synthesize m_nsWCBGImgObjectID;
@property(retain, nonatomic) NSString *m_nsWeiDianInfo; // @synthesize m_nsWeiDianInfo;
@property(retain, nonatomic) NSString *m_nsWeiboAddress; // @synthesize m_nsWeiboAddress;
@property(retain, nonatomic) NSString *m_nsWeiboNickName; // @synthesize m_nsWeiboNickName;
@property(retain, nonatomic) NSString *m_nsWorkID; // @synthesize m_nsWorkID;
@property(retain, nonatomic) NSString *m_pcWCBGImgID; // @synthesize m_pcWCBGImgID;
@property(nonatomic) unsigned int m_uiBrandSubscriptionSettings; // @synthesize m_uiBrandSubscriptionSettings;
@property(nonatomic) unsigned int m_uiCertificationFlag; // @synthesize m_uiCertificationFlag;
@property(nonatomic) unsigned int m_uiChatRoomMaxCount; // @synthesize m_uiChatRoomMaxCount;
@property(nonatomic) unsigned int m_uiChatRoomStatus; // @synthesize m_uiChatRoomStatus;
@property(nonatomic) unsigned int m_uiChatRoomVersion; // @synthesize m_uiChatRoomVersion;
@property(nonatomic) unsigned int m_uiDeleteFlag; // @synthesize m_uiDeleteFlag;
@property(nonatomic) unsigned int m_uiNeedUpdate; // @synthesize m_uiNeedUpdate;
@property(nonatomic) unsigned int m_uiWeiboFlag; // @synthesize m_uiWeiboFlag;
- (_Bool)needShowUnreadCountOnSession;
- (void)setChatRoomDataWithoutEmojiChange:(id)arg1;
- (void)setChatStatusNotifyOpen:(_Bool)arg1;
- (void)setExternalInfoJSONCache:(id)arg1;
- (void)setSignatureWithoutEmojiChange:(id)arg1;
- (void)tryLoadExtInfo;
- (id)xmlForMessageWrapContent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;

@end

