
#import "CContact.h"

@interface CContactMgr : NSObject
{
    unsigned int m_uiLoadedType;
    NSMutableDictionary *m_dicContacts;
    NSMutableDictionary *m_dicEncodeContacts;
    _Bool m_bDataNeedReload;
    NSMutableDictionary *m_mapLastGetTime;
    NSMutableDictionary *m_dicHardCodeUsers;
    unsigned int m_uiDBVersion;
    CContact *m_oSelfContact;
    _Bool m_bIsSelfContactUpdated;
}

- (_Bool)ChangeNotifyStatus:(id)arg1 withStatus:(_Bool)arg2 sync:(_Bool)arg3;
- (_Bool)ChangeNotifyStatusForChatRoom:(id)arg1 withStatus:(_Bool)arg2 sync:(_Bool)arg3;
- (unsigned int)GetFriendMetaFlag:(id)arg1;
- (id)HandleMemContact:(id)arg1;
- (void)MainThread_ReloadMemContact:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)MessageReturn:(unsigned int)arg1 MessageInfo:(id)arg2 Event:(unsigned int)arg3;
- (_Bool)RemoveContactFromChatList:(id)arg1;
- (_Bool)SetFriendMetaFlag:(unsigned int)arg1 ForUser:(id)arg2;
- (_Bool)addContact:(id)arg1 AtUser:(id)arg2;
- (_Bool)addContact:(id)arg1 listType:(unsigned int)arg2;
- (_Bool)addContact:(id)arg1 listType:(unsigned int)arg2 addScene:(unsigned int)arg3 sync:(_Bool)arg4;
- (_Bool)addContact:(id)arg1 listType:(unsigned int)arg2 sync:(_Bool)arg3;
- (void)addContactInternal:(id)arg1;
- (_Bool)addFromMobileContact:(id)arg1;
- (_Bool)addFromQQContact:(id)arg1;
- (_Bool)addLocalContact:(id)arg1 listType:(unsigned int)arg2;
- (_Bool)addMMContact:(id)arg1;
- (void)addMacHelperContact;
- (_Bool)addSXContact:(id)arg1;
- (void)addToGetContactMap:(id)arg1;
- (void)callModifyContactForCPState:(id)arg1;
- (_Bool)checkIfForbiddenGetContact:(id)arg1;
- (_Bool)delayLoadAllContactInBackGround;
- (_Bool)deleteAtUserList:(id)arg1;
- (_Bool)deleteContact:(id)arg1 listType:(unsigned int)arg2;
- (_Bool)deleteContact:(id)arg1 listType:(unsigned int)arg2 andScene:(unsigned int)arg3 sync:(_Bool)arg4;
- (_Bool)deleteContact:(id)arg1 listType:(unsigned int)arg2 sync:(_Bool)arg3;
- (void)fixContactPluginOldData;
- (id)getAllBrandContacts;
- (id)getAllEnterpriseMainBrandContacts;
- (id)getContact:(id)arg1 listType:(unsigned int)arg2 contactType:(unsigned int)arg3;
- (id)getContactByName:(id)arg1;
- (id)getContactByNameForce:(id)arg1;
- (id)getContactByNameFromCache:(id)arg1;
- (id)getContactByNameFromDB:(id)arg1;
- (id)getContactByNameNotMySelf:(id)arg1;
- (unsigned int)getContactCount:(unsigned int)arg1 contactType:(unsigned int)arg2 domain:(id)arg3;
- (id)getContactList:(unsigned int)arg1 contactType:(unsigned int)arg2 domain:(id)arg3;
- (id)getContactList:(unsigned int)arg1 contactType:(unsigned int)arg2 domain:(id)arg3 needLoadExt:(_Bool)arg4;
- (id)getContactListInChatroom;
- (_Bool)getContactsFromServer:(id)arg1;
- (_Bool)getContactsFromServer:(id)arg1 chatContact:(id)arg2;
- (_Bool)getContactsFromSvrForTempChat:(id)arg1;
- (id)getGroupCardMemberList:(id)arg1;
- (id)getSelfContact;
- (void)initDB:(id)arg1 lock:(id)arg2;
- (_Bool)internalGetContactsFromSvr:(id)arg1 chatContact:(id)arg2 usrData:(id)arg3;
- (_Bool)isBelongToMMContactInCache:(id)arg1;
- (_Bool)isContactBlack:(id)arg1;
- (_Bool)isContactExist:(id)arg1 listType:(unsigned int)arg2 contactType:(unsigned int)arg3;
- (_Bool)isHeadImgUpdated:(id)arg1 Local:(id)arg2;
- (_Bool)isInContactList:(id)arg1;
- (_Bool)isLastUpdateTimeExpired:(id)arg1;
- (void)main_onPushAddContact:(id)arg1;
- (void)main_onPushBatchModContact:(id)arg1;
- (void)main_onPushDeleteContact:(id)arg1;
- (void)main_onPushModifyContact:(id)arg1;
- (_Bool)modifyContactNickName:(id)arg1 nickName:(id)arg2;
- (void)onBrandContactModified:(id)arg1 withAttrChanged:(id)arg2;
- (void)onGetContact:(id)arg1;
- (void)onLanguageChange;
- (void)onServiceClearData;
- (_Bool)onServiceMemoryWarning;
- (void)onServiceReloadData;
- (void)onSettingChange;
- (void)reloadContact:(id)arg1;
- (void)reloadContactImageStatus:(id)arg1 Status:(id)arg2 Image:(id)arg3;
- (void)removeMacHelperContact;
- (_Bool)setBlack:(id)arg1;
- (_Bool)setBlack:(id)arg1 blackFlag:(_Bool)arg2 sync:(_Bool)arg3;
- (_Bool)setBlack:(id)arg1 sync:(_Bool)arg2;
- (_Bool)setContact:(id)arg1 RoomDetail:(id)arg2;
- (_Bool)setContact:(id)arg1 cardDesc:(id)arg2;
- (_Bool)setContact:(id)arg1 cardUrl:(id)arg2;
- (_Bool)setContact:(id)arg1 chatRoomData:(id)arg2;
- (_Bool)setContact:(id)arg1 chatState:(unsigned int)arg2;
- (_Bool)setContact:(id)arg1 draft:(id)arg2;
- (_Bool)setContact:(id)arg1 favour:(_Bool)arg2 sync:(_Bool)arg3;
- (_Bool)setContact:(id)arg1 googleContactName:(id)arg2;
- (_Bool)setContact:(id)arg1 googleContactNickName:(id)arg2;
- (_Bool)setContact:(id)arg1 hideHashPhone:(_Bool)arg2 sync:(_Bool)arg3;
- (_Bool)setContact:(id)arg1 mobileIdentify:(id)arg2;
- (_Bool)setContact:(id)arg1 nickName:(id)arg2;
- (_Bool)setContact:(id)arg1 notifyOpen:(_Bool)arg2 sync:(_Bool)arg3;
- (_Bool)setContact:(id)arg1 owner:(id)arg2;
- (_Bool)setContact:(id)arg1 remark:(id)arg2;
- (_Bool)setContact:(id)arg1 remark:(id)arg2 hideHashPhone:(_Bool)arg3;
- (_Bool)setContact:(id)arg1 sessionTop:(_Bool)arg2 sync:(_Bool)arg3;
- (_Bool)setContact:(id)arg1 snsBlack:(_Bool)arg2;
- (_Bool)setContact:(id)arg1 textTranslateOpen:(_Bool)arg2 sync:(_Bool)arg3;
- (_Bool)setContact:(id)arg1 typeBit:(unsigned int)arg2 set:(_Bool)arg3 sync:(_Bool)arg4;
- (_Bool)setContact:(id)arg1 typeBit:(unsigned int)arg2 set:(_Bool)arg3 sync:(_Bool)arg4 localSet:(_Bool)arg5;
- (_Bool)setContact:(id)arg1 watchContact:(_Bool)arg2 sync:(_Bool)arg3;
- (_Bool)setHDHeadUpdated:(id)arg1;
- (_Bool)setLocalContact:(id)arg1 notifyOpen:(_Bool)arg2;
- (_Bool)setNoBlack:(id)arg1;
- (_Bool)setNoBlack:(id)arg1 sync:(_Bool)arg2;
- (_Bool)setPhone:(id)arg1 Contact:(id)arg2;
- (void)setSelfContactUpdated;
- (_Bool)shouldUpdateContact:(id)arg1;
- (_Bool)syncAllSXContact;
- (id)thread_HandleMemContact:(id)arg1;
- (void)thread_ReloadMemConact:(id)arg1 ChatRoom:(id)arg2;
- (id)thread_onBatchModifyChatRoomMember:(id)arg1;
- (_Bool)thread_onPushDeleteContact:(id)arg1;
- (_Bool)thread_onPushModifyContact:(id)arg1 isInit:(_Bool)arg2;
- (id)thread_onpushBatchModContact:(id)arg1;
- (void)thread_saveContactImageStatus:(id)arg1 Status:(id)arg2 Image:(id)arg3;
- (void)tryLoadExtInfoForContact:(id)arg1;
- (void)updateContactLocalData;
- (_Bool)updateContactToCache:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@end

